### ISSUE TITLE
camel-xchange can no longer access the Binance market endpoint

### ISSUE THREAD

**Issue by tdiesler** [fuse-boosters/fuse-booster-camel-quarkus-ticker-amq-kafka#15]
```
2021-09-23 14:04:49,808 WARN  [si.maz.res.ResponseReader] (main) Noncritical error parsing error output: This endpoint has been deprecated, please integrate with ?GET@/sapi/v1/asset/assetDetail?. See details in the announcement: https://www.binance.com/en/support/announcement/f45dde7da58b473aa885349946be...: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'This': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"This endpoint has been deprecated, please integrate with ?GET@/sapi/v1/asset/assetDetail?. See details in the announcement: https://www.binance.com/en/support/announcement/f45dde7da58b473aa885349946bed269"; line: 1, column: 5]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2337)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:720)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2903)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1949)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:781)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4684)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4586)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3548)
	at si.mazi.rescu.serialization.jackson.JacksonResponseReader.read(JacksonResponseReader.java:53)
	at si.mazi.rescu.serialization.jackson.JacksonResponseReader.readException(JacksonResponseReader.java:58)
	at si.mazi.rescu.ResponseReader.read(ResponseReader.java:82)
	at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:179)
	at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:167)
	at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:123)
	at com.sun.proxy.$Proxy21.assetDetail(Unknown Source)
	at org.knowm.xchange.binance.service.BinanceAccountServiceRaw.lambda$requestAssetDetail$4(BinanceAccountServiceRaw.java:115)
	at org.knowm.xchange.client.ResilienceUtils$DecorateCallableApi.call(ResilienceUtils.java:74)
	at org.knowm.xchange.binance.service.BinanceAccountServiceRaw.requestAssetDetail(BinanceAccountServiceRaw.java:119)
	at org.knowm.xchange.binance.service.BinanceAccountService.getAssetDetails(BinanceAccountService.java:177)
	at org.knowm.xchange.binance.BinanceExchange.remoteInit(BinanceExchange.java:101)
	at org.knowm.xchange.BaseExchange.applySpecification(BaseExchange.java:113)
	at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:110)
	at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:53)
	at org.apache.camel.component.xchange.XChangeComponent.createXChange(XChangeComponent.java:64)
	at org.apache.camel.component.xchange.XChangeComponent.createEndpoint(XChangeComponent.java:45)
```

**Comment by tdiesler** [comment]
https://issues.apache.org/jira/browse/CAMEL-16872
https://github.com/apache/camel/commit/decf7f0cf70f68dd225e96c372f1289041f36d01
